Added required="true" attribute to nodes ground_truth_republisher, ground_truth_to_rpy and mag_republisher in simulation_low.launch
RoboJackets/igvc-software pull request #785
Opened 2020-10-25 23:54 UTC by calebkm

# Description

## TWO ITEMS NOT YET COMPLETED!
1) This code hasn't been tested. I'm not sure how to do that part :-) Will update the PR once I've gotten feedback and completed testing.
2) When running `make format` I get big long error culminating in the below. Help super appreciated!
```
make: clang-format: No such file or directory
make: *** [format] Error 1
```
#### Thanks ya'll!
---

This PR adds `required="true"` to nodes in `simulation_low.launch`.

Nodes updated:
- ground_truth_republisher
- mag_republisher
- ground_truth_to_rpy

Fixes #754 

# Testing steps (If relevant)

# Self Checklist
- [ ] I have formatted my code using `make format`
- [ ] I have tested that the new behaviour works

2020-10-26 00:40 UTC, oswinso commented
@calebkm 
Regarding the `clang-format` error, you just need to install `clang-format`. You can either install just `clang-format` via
```bash
sudo apt install clang-format
```

or via the setup script:
```bash
cd igvc-software
./install_dependencies.sh
```

2020-10-26 01:14 UTC, calebkm commented
Thanks, @oswinso! I also realized that this work is likely best done via the RoboJackets VM :-P I've been working on my local OSX machine for these PRs. ***Slaps self on forehead***

2020-10-26 14:18 UTC, matthewhannay567 requested changes
Change the base of PR to `noetic-migration`, because that's the current working branch.

2020-10-30 18:50 UTC, calebkm commented
Closing this out. New PR here: https://github.com/RoboJackets/igvc-software/pull/786

2020-10-30 18:50 UTC, closed without merging