Feat/pointcloud clustering
RoboJackets/igvc-software pull request #818
Opened 2020-12-20 03:20 UTC by yyajima21

# Description
This project contains a software package that segments lidar point cloud into clusters and creates a bounding box over each cluster in real time. This package adds a feature to localize objects surrounded by the robot such as barrels and people.

This PR does the following:
- Ground plane segmentation
- Point cloud clustering that categorizes lidar points into several clusters using two well known method (region growing and euclidean clustering methods)
- Visualization tool that creates a bounding box over each clusters

Fixes  #777 and #651 

# Testing steps (If relevant)
## Test Case 1
1. Download a bag file (e.g. JESSII_RUN_SUN_2_2019-06-10-15-30-13.bag) from the robojacket cloud
2. Modify launch file and add your file path
3. Run the following command to visualize the point cloud segmentation.
`roslaunch igvc_perception ptseg.launch` 

Expectation: You should see the following result in your rviz screen. Each cluster has its own bounding box.

![image](https://user-images.githubusercontent.com/35343680/102704314-caf38400-4247-11eb-9914-3d48a144c613.png)

# Self Checklist
- [ ] I have formatted my code using `make format`
- [ ] I have tested that the new behavior works

2021-01-03 03:34 UTC, andrewyarovoi requested changes
Overall, this code looks good. The main thing is that there are a lot of hard coded parameters. These should be added to the pointcloud_filter.yaml file and then should be passed in to the util functions. That way, they can be tuned without requiring rebuilding the project and they can all be in one place (with comments and units).

2021-01-03 03:34 UTC, andrewyarovoi commented on igvc_perception/src/pointcloud_segmentation/ground_filter.cpp
> +  const auto& z = 2.0;
These values should be pulled from a configuration file instead of being hard coded

2021-01-03 03:34 UTC, andrewyarovoi commented on igvc_perception/src/pointcloud_segmentation/utils.h
> +  reg.setMaxClusterSize(300);
Similarly, all of the parameters for region growing should probably, be inputs to this functions, and the inputs should be populated by the calling function by getting the values from a configuration file.

2021-01-03 03:34 UTC, andrewyarovoi commented on igvc_perception/src/pointcloud_segmentation/utils.h
> +  sor.setMeanK(50);
again, this should be an input and the value should be set from a configuration file.

2021-01-04 02:03 UTC, yyajima21 commented on igvc_perception/src/pointcloud_segmentation/README.md
> +This repository contains a point cloud clustering package that clusters raw point cloud data into sevral objects.
Thanks for your review! I updated the readme file based on your suggestion.

2021-01-07 15:21 UTC, yyajima21 commented on igvc_perception/src/pointcloud_segmentation/utils.h
> +  ec.setMaxClusterSize(300);
I added a yaml file that has options to set default config values.

2021-01-07 17:08 UTC, yyajima21 commented
@andrewyarovoi I removed hard coded values based on your feedback.

2021-01-07 22:47 UTC, andrewyarovoi approved these changes
Thanks for addressing my comments. Everything looks good now. Great job!

2021-01-07 22:47 UTC, merged